#     PROGRAMA PARA REGRESI?N MULTIPLE
#     Automoviles DE CLASE
#
#     Profr. Francisco S?nchez Villarreal
# ..................................................................................................................................

#	AJUSTAR LA RUTA DE SU CARPETA CON ARCHIVO DE DATOS

Automoviles<-read.csv(choose.files())

Automoviles

attach(Automoviles)

#	SE GRAFICAN DIAGRAMAS DE DISPERSI?N POR PARES
pairs(Automoviles)

#	SE CALCULAN COEFICIENTES DE CORRELACI?N SIMPLES

MATRIZ_COR<-cor(Automoviles)

data.frame(MATRIZ_COR)


#  SE AJUSTA MODELO DE REGRESION MULTIPLE

MODELO<-lm(Y~X1+X2)

MODELO

names(MODELO)

COEFICIENTES<-coefficients(MODELO)

COEFICIENTES

#	MATRIZ DE VARIANZAS Y COVARIANZAS DE COEFICIENTES DEL MODELO

vcov(MODELO)

#	TABLA RESUMEN DE COEFICIENTES DEL MODELO

summary(MODELO)


#	INTERVALOS DE 96% DE CONFIANZA PARA COEFICIENTES DE MODELO

INTERVALOS<-confint(MODELO, level = 0.95)

INTERVALOS

#	ANOVA DEL MODELO CONTRIBUCIONES DE VARIABLES POR SERPARADO

ANOVA_MODELO<-anova(MODELO)

ANOVA_MODELO

ANOVA2<-aov(MODELO)
ANOVA2

#  SE CALCULAN VALORES ESTIMADOS PARA Y

ESTIMADOS<-fitted(MODELO)

ESTIMADOS

plot(Y,ESTIMADOS)

#	CORRELACI?N M?LTIPLE OBTENIDA COMO CORRELACI?N SIMPLE ENTRE ESTIMADOS Y OBSERVADOS

cor(ESTIMADOS,Y)


########### INTERVALO DE CONFIANZA PARA VALORES MEDIOS Y PUNTUALES DE  Y

#	SE INTEGRAN VARIABLES INDEPENDIENTES EN UNA TABLA

VALORES<-data.frame(X1,X2)

VALORES

#	INTERVALO DE CONFIANZA PARA VALORES MEDIOS DE Y

IC_MEDIOS<-predict(MODELO,newdata=VALORES,interval="confidence",level=0.95)

IC_MEDIOS

#	INTERVALO DE CONFIANZA PARA VALORES PUNTUALES DE Y
 

IC_PUNTUALES<-predict(MODELO,newdata=VALORES,interval="prediction",level=0.95)

IC_PUNTUALES


##	AN?LISIS DE RESIDUALES

#	SE OBTIENEN LOS RESIDUALES

RESIDUALES<-residuals(MODELO)

RESIDUALES

# 	SE VERIFICA GR?FICAMENTE NORMALIDAD DE RESIDUALES Y RECTA IDENTICA

qqnorm(RESIDUALES)
qqline(RESIDUALES)

##	SE PRUEBA NORMALIDAD DE RESIDUALES MEDIANTE PRUEBA DE JARQUE BERA

library(tseries)

jarque.bera.test(RESIDUALES)


#	ERROR EST?NDAR DE RESIDUALES


EE_RES<-sqrt(var(RESIDUALES)*(9-1)/(9-3))

EE_RES


#	SE OBTIENEN RESIDUALES ESTANDARIZADOS

RES_ESTAN<-RESIDUALES/EE_RES

RES_ESTAN


#  SE OBTIENEN  RESIDUALES ESTUDENTIZADOS 

RESESTUDENT<-rstandard(MODELO)

RESESTUDENT


### 	Se detectan VALORES INFLUYENTES mediante Distancia de Cook, Leverage(H hat)y Mahalanovis

COOK<-cooks.distance(MODELO)

COOK


# 	Para hacerla comparable a SPSS hay que agregar 1/n a cada elemento de la diagonal H en SPSS

HAT<-hatvalues(MODELO)

HAT

#  Distancia Mahalanobis

MAHA<-(9-1)*(HAT-1/9)

MAHA














